version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3014:8080"
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - API_TOKEN=${API_TOKEN:sk-114514}
    volumes:
      - ./:/app
